-- Create game_records table
CREATE TABLE IF NOT EXISTS game_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  level INTEGER NOT NULL,
  mode TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  cleared BOOLEAN DEFAULT false,
  cleared_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create unique index for upsert logic
-- Ensures one record per user per specific game configuration
CREATE UNIQUE INDEX IF NOT EXISTS idx_game_records_unique_play 
ON game_records (user_id, category, subject, level, mode);

-- Enable Row Level Security
ALTER TABLE game_records ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own records
CREATE POLICY "Users can view own records" 
ON game_records FOR SELECT 
USING (auth.uid() = user_id);

-- Policy: Users can insert their own records
CREATE POLICY "Users can insert own records" 
ON game_records FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own records
CREATE POLICY "Users can update own records" 
ON game_records FOR UPDATE 
USING (auth.uid() = user_id);

-- Optional: Trigger to automatically update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_game_records_updated_at
    BEFORE UPDATE ON game_records
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
