-- Create game_records table
CREATE TABLE IF NOT EXISTS game_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  level INTEGER NOT NULL,
  mode TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  cleared BOOLEAN DEFAULT false,
  cleared_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, category, subject, level, mode)
);

-- Update auth.users with game specific columns (handled via public.users table for RLS)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  minerals INTEGER DEFAULT 0,
  stamina INTEGER DEFAULT 5,
  last_stamina_update TIMESTAMP WITH TIME ZONE DEFAULT now(),
  best_score_timeattack INTEGER DEFAULT 0,
  best_score_survival INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create items table
CREATE TABLE IF NOT EXISTS public.items (
  id INTEGER PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  price INTEGER NOT NULL,
  description TEXT,
  category TEXT -- 'equip', 'trigger'
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES public.items(id),
  quantity INTEGER DEFAULT 0,
  UNIQUE(user_id, item_id)
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public items are viewable by everyone" ON public.items FOR SELECT USING (true);
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can view own inventory" ON public.inventory FOR SELECT USING (auth.uid() = user_id);

-- Initial items data
INSERT INTO public.items (id, code, name, price, description, category)
VALUES 
  (101, 'oxygen_tank', '산소통', 500, '제한 시간 +10초', 'equip'),
  (102, 'power_gel', '파워젤', 300, '시작 시 모멘텀(콤보1) 활성', 'equip'),
  (103, 'safety_rope', '안전 로프', 1000, '오답 1회 방어', 'equip'),
  (201, 'flare', '구조 신호탄', 800, '게임 오버 시 부활', 'trigger')
ON CONFLICT (id) DO NOTHING;
