import type { BgmTheme } from '../types';
import type { BgmTrackArrangement } from './types';

export const BGM_ARRANGEMENTS_V2: Record<BgmTheme, BgmTrackArrangement> = {
  brain_age: {
    totalSteps: 384,
    bpm: 106,
    stepDuration: 0.1415,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 라운지 인트로',
        startStep: 0,
        endStep: 95,
        instruments: ['🎻 워킹 콘트라베이스', '🎹 웜 로즈 피아노'],
        description: '시부야계 재즈 라운지 베이스와 텐션 코드 컴핑',
      },
      {
        partNum: 2,
        name: 'Part 2: 스윙 브러쉬 드럼',
        startStep: 96,
        endStep: 191,
        instruments: ['🎻 워킹 베이스', '🎹 로즈 피아노', '🥁 브러쉬 스네어 & 하이햇'],
        description: '60/40 셔플 스윙 리듬과 하이햇 칙-칙 스윙 드라이브',
      },
      {
        partNum: 3,
        name: 'Part 3: 비브라폰 듀엣 솔로',
        startStep: 192,
        endStep: 287,
        instruments: ['🎻 워킹 베이스', '🎹 로즈 피아노', '🥁 브러쉬 드럼', '🔔 비브라폰 솔로'],
        description: '청량한 비브라폰 멜로디와 입체적 아르페지오 전개',
      },
      {
        partNum: 4,
        name: 'Part 4: 풀 앙상블 턴어라운드',
        startStep: 288,
        endStep: 383,
        instruments: ['🎻 풀 베이스', '🎹 풀 로즈', '🥁 풀 스윙 드럼', '🔔 비브라폰 잼'],
        description: '모든 악기가 어우러지는 피날레 잼 세션',
      },
    ],
  },
  celeste: {
    totalSteps: 512,
    bpm: 118,
    stepDuration: 0.1271,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 고요한 산기슭',
        startStep: 0,
        endStep: 127,
        instruments: ['🎹 First Steps 피아노 아르페지오'],
        description: '서정적이고 맑은 피아노 단독 등반 모티프',
      },
      {
        partNum: 2,
        name: 'Part 2: 등반의 심장박동',
        startStep: 128,
        endStep: 255,
        instruments: ['🎹 피아노', '🥁 4-on-Floor 킥 드럼', '⚡ 신스베이스'],
        description: '심장박동 같은 4박 킥과 묵직한 베이스 추가',
      },
      {
        partNum: 3,
        name: 'Part 3: 본격적인 절벽 등반',
        startStep: 256,
        endStep: 383,
        instruments: ['🎹 피아노', '🥁 킥 드럼', '⚡ 베이스', '🧗‍♀️ 슈퍼쏘우 리드 멜로디'],
        description: '감정선이 고조되는 메인 등반 멜로디 라인 등장',
      },
      {
        partNum: 4,
        name: 'Part 4: 정상 정복 클라이맥스',
        startStep: 384,
        endStep: 511,
        instruments: ['🎹 피아노', '🥁 파워 드럼', '⚡ 베이스', '🧗‍♀️ 풀 신스 오케스트라'],
        description: '모든 레이어가 만개하는 벅찬 정상 정복 피날레',
      },
    ],
  },
  climb: {
    totalSteps: 384,
    bpm: 124,
    stepDuration: 0.121,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 사이버펑크 시동',
        startStep: 0,
        endStep: 95,
        instruments: ['⚡ 16비트 모듈러 베이스', '🥁 124BPM 킥'],
        description: '질주하는 16비트 아날로그 모듈러 베이스라인',
      },
      {
        partNum: 2,
        name: 'Part 2: 네온 아르페지오',
        startStep: 96,
        endStep: 191,
        instruments: ['⚡ 모듈러 베이스', '🥁 킥', '✨ 16분 신스 아르페지오'],
        description: '화려한 네온 사인을 가르는 아르페지오 드라이브',
      },
      {
        partNum: 3,
        name: 'Part 3: 슈퍼쏘우 피버',
        startStep: 192,
        endStep: 287,
        instruments: ['⚡ 베이스', '🥁 킥', '✨ 아르페지오', '🔥 슈퍼쏘우 스탭 & 리드'],
        description: '폭발적인 쏘우투스 코드 스탭과 질주 멜로디',
      },
      {
        partNum: 4,
        name: 'Part 4: 하이퍼 드라이브',
        startStep: 288,
        endStep: 383,
        instruments: ['⚡ 풀 베이스', '🥁 풀 드럼', '✨ 아르페지오', '🔥 풀 신스 피버'],
        description: '한계 속도로 돌파하는 최고 출력 사이버 질주',
      },
    ],
  },
  shop: {
    totalSteps: 384,
    bpm: 102,
    stepDuration: 0.147,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 아늑한 보사노바 베이스',
        startStep: 0,
        endStep: 95,
        instruments: ['🎸 보사노바 베이스', '🪕 기타 스트럼'],
        description: '포근하고 따뜻한 산악 만물상 베이스와 기타 반주',
      },
      {
        partNum: 2,
        name: 'Part 2: 16비트 퍼커션',
        startStep: 96,
        endStep: 191,
        instruments: ['🎸 베이스 & 기타', '🪇 16비트 셰이커', '🪵 우드블록 림샷'],
        description: '사각거리는 셰이커와 경쾌한 우드블록 퍼커션 추가',
      },
      {
        partNum: 3,
        name: 'Part 3: 멜로디카 & 실로폰',
        startStep: 192,
        endStep: 287,
        instruments: ['🎸 베이스 & 기타', '🪇 셰이커', '🎹 빈티지 멜로디카', '🔔 실로폰'],
        description: '아기자기하고 귀여운 멜로디카 듀엣 선율',
      },
      {
        partNum: 4,
        name: 'Part 4: 포근한 만물상 앙상블',
        startStep: 288,
        endStep: 383,
        instruments: ['🎸 풀 기타 & 베이스', '🪇 풀 퍼커션', '🎹 멜로디카 하모니'],
        description: '모든 악기가 어우러지는 따뜻한 휴식처의 완성',
      },
    ],
  },
  victory: {
    totalSteps: 384,
    bpm: 108,
    stepDuration: 0.1389,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 승리의 팡파르 화음',
        startStep: 0,
        endStep: 95,
        instruments: ['🎺 브라스 섹션', '✨ 천상의 하프 글리산도'],
        description: '찬란한 승리를 알리는 팡파르와 하프 아르페지오',
      },
      {
        partNum: 2,
        name: 'Part 2: 마칭 스네어 & 팀파니',
        startStep: 96,
        endStep: 191,
        instruments: ['🎺 브라스 & 하프', '🥁 마칭 스네어 롤', '💥 오케스트라 팀파니'],
        description: '웅장한 행진 리듬과 심장을 울리는 팀파니 타격',
      },
      {
        partNum: 3,
        name: 'Part 3: 트럼펫 개선 행진곡',
        startStep: 192,
        endStep: 287,
        instruments: ['🎺 트럼펫 리드 솔로', '🥁 마칭 퍼커션', '✨ 하프 글리산도'],
        description: '정상에 우뚝 선 등반가를 위한 개선가 멜로디',
      },
      {
        partNum: 4,
        name: 'Part 4: 대형 오케스트라 튜티',
        startStep: 288,
        endStep: 383,
        instruments: ['🎺 풀 브라스', '🥁 풀 마칭 드럼 & 팀파니', '✨ 풀 하프 앙상블'],
        description: '모든 악기가 최대 음량으로 울려 퍼지는 영광의 순간',
      },
    ],
  },
  crisis: {
    totalSteps: 448,
    bpm: 132,
    stepDuration: 0.1136,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 심장박동 & 초침 째깍',
        startStep: 0,
        endStep: 111,
        instruments: ['💓 쿵-쾅 더블 심장박동', '⏱️ 16비트 시계 초침 째깍'],
        description: '스태미나 고갈 직전의 미니멀 심장박동 서스펜스',
      },
      {
        partNum: 2,
        name: 'Part 2: 서브 펄스 & 텐션 패드',
        startStep: 112,
        endStep: 223,
        instruments: ['💓 심장박동', '⏱️ 초침', '⚡ 서브 베이스 펄스', '🌫️ 텐션 디미니쉬 패드'],
        description: '어두운 텐션 코드와 묵직한 서브 펄스의 압박감',
      },
      {
        partNum: 3,
        name: 'Part 3: 비상 사이렌 & 크로매틱 하강',
        startStep: 224,
        endStep: 335,
        instruments: ['💓 심장박동', '🚨 비상 경보 사이렌', '⚡ 크로매틱 하강 베이스'],
        description: '추락 위기를 알리는 날카로운 경보음과 하강 베이스',
      },
      {
        partNum: 4,
        name: 'Part 4: 긴급 카운트다운 서스펜스',
        startStep: 336,
        endStep: 447,
        instruments: ['💓 최대 맥박', '🚨 풀 사이렌', '⚡ 풀 서스펜스 신스'],
        description: '마지막 1초를 다투는 극한의 라스트 찬스 긴장감',
      },
    ],
  },
  puzzle: {
    totalSteps: 384,
    bpm: 84,
    stepDuration: 0.1785,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 빈티지 테이프 로즈',
        startStep: 0,
        endStep: 95,
        instruments: ['🎹 Lo-Fi 테이프 새츄레이션 로즈 건반'],
        description: '따뜻하고 아늑한 스터디 비트 재즈 코드 진행',
      },
      {
        partNum: 2,
        name: 'Part 2: 95Hz 더스티 붐뱁 드럼',
        startStep: 96,
        endStep: 191,
        instruments: ['🎹 로즈 피아노', '🥁 95Hz 로우패스 킥 & 1800Hz 림샷'],
        description: '고개를 끄덕이게 만드는 Lo-Fi 붐뱁 힙합 드럼 그루브',
      },
      {
        partNum: 3,
        name: 'Part 3: 딥 서브 베이스 & 마림바',
        startStep: 192,
        endStep: 287,
        instruments: ['🎹 로즈 건반', '🥁 붐뱁 드럼', '🎻 딥 서브 베이스', '🔔 마림바 테마'],
        description: '묵직한 서브 저음과 은은한 마림바 선율 조화',
      },
      {
        partNum: 4,
        name: 'Part 4: 풀 Lo-Fi 칠홉 그루브',
        startStep: 288,
        endStep: 383,
        instruments: ['🎹 풀 로즈', '🥁 풀 붐뱁 비트', '🎻 서브 베이스', '🔔 칠홉 앙상블'],
        description: '뇌파를 안정시키고 깊은 몰입감을 선사하는 풀 비트',
      },
    ],
  },
  chill: {
    totalSteps: 256,
    bpm: 76,
    stepDuration: 0.1974,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 고요한 오스티나토',
        startStep: 0,
        endStep: 63,
        instruments: ['🪵 엇박 아날로그 오스티나토'],
        description: '3+3+2 당김음 리듬으로 굴러가는 맑고 따뜻한 F Lydian 건반',
      },
      {
        partNum: 2,
        name: 'Part 2: 부유하는 웜 서브',
        startStep: 64,
        endStep: 127,
        instruments: ['🪵 아날로그 오스티나토', '⚡ 웜 서브 펄스'],
        description: '공중에 붕 뜨듯 기분 좋게 받쳐주는 아날로그 서브 베이스',
      },
      {
        partNum: 3,
        name: 'Part 3: 아날로그 스트링 패드',
        startStep: 128,
        endStep: 191,
        instruments: ['🪵 오스티나토', '⚡ 서브 펄스', '🌫️ 필터드 아날로그 패드'],
        description: '저역에서 서서히 열리는 따뜻한 공기감의 아날로그 패드',
      },
      {
        partNum: 4,
        name: 'Part 4: 카운터 하모닉스 블룸',
        startStep: 192,
        endStep: 255,
        instruments: ['🪵 풀 오스티나토', '⚡ 풀 서브', '🌫️ 풀 패드', '✨ 카운터 하모닉스'],
        description: '오스티나토 틈새로 부드럽게 번지는 배음과 감동의 피날레',
      },
    ],
  },
  arcade: {
    totalSteps: 512,
    bpm: 136,
    stepDuration: 0.1103,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: NES 펄스 1 단독 리드',
        startStep: 0,
        endStep: 127,
        instruments: ['👾 NES 2A03 Pulse 1 메인 리드'],
        description: '정통 8비트 패미컴 1채널 레트로 멜로디',
      },
      {
        partNum: 2,
        name: 'Part 2: 트라이앵글 롤링 베이스 & 노이즈 드럼',
        startStep: 128,
        endStep: 255,
        instruments: ['👾 Pulse 1 리드', '📐 NES Triangle 롤링 베이스', '🥁 Noise 버퍼 드럼'],
        description: '계단식 롤링 베이스와 바삭한 화이트노이즈 스네어 추가',
      },
      {
        partNum: 3,
        name: 'Part 3: 펄스 2 고속 아르페지오',
        startStep: 256,
        endStep: 383,
        instruments: ['👾 Pulse 1&2 듀얼 신스', '📐 Triangle 베이스', '🥁 Noise 드럼'],
        description: '2채널 펄스파의 현란한 고속 아르페지오 속도감',
      },
      {
        partNum: 4,
        name: 'Part 4: 4채널 풀 칩튠 앤섬',
        startStep: 384,
        endStep: 511,
        instruments: ['👾 Dual Pulse Lead', '📐 Triangle Rolling Bass', '🥁 Noise Drum Beat'],
        description: '패미컴 사운드칩의 한계를 끌어낸 8비트 보스전 앤섬',
      },
    ],
  },
};

export const BGM_ARRANGEMENTS_V1: Record<BgmTheme, BgmTrackArrangement> = {
  brain_age: {
    totalSteps: 64,
    bpm: 104,
    stepDuration: 0.1442,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: Cmaj9 워킹베이스',
        startStep: 0,
        endStep: 15,
        instruments: ['🎻 워킹 베이스', '🎹 재즈 컴핑'],
        description: 'Cmaj9 코드 워킹베이스와 재즈 컴핑',
      },
      {
        partNum: 2,
        name: 'Part 2: A7(b13) 전개',
        startStep: 16,
        endStep: 31,
        instruments: ['🎻 워킹 베이스', '🎹 재즈 컴핑', '🥁 하이햇'],
        description: 'A7(b13) 코드 진행과 스윙 하이햇',
      },
      {
        partNum: 3,
        name: 'Part 3: Dm9 투파이브',
        startStep: 32,
        endStep: 47,
        instruments: ['🎻 워킹 베이스', '🎹 재즈 컴핑'],
        description: 'Dm9 2-5 코드 진행',
      },
      {
        partNum: 4,
        name: 'Part 4: G13 턴어라운드',
        startStep: 48,
        endStep: 63,
        instruments: ['🎻 워킹 베이스', '🎹 재즈 컴핑', '🥁 하이햇'],
        description: 'G13 도미넌트 턴어라운드 순환',
      },
    ],
  },
  celeste: {
    totalSteps: 128,
    bpm: 118,
    stepDuration: 0.1271,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: First Steps C-G',
        startStep: 0,
        endStep: 31,
        instruments: ['🎹 피아노 아르페지오'],
        description: '서정적 C-G 아르페지오',
      },
      {
        partNum: 2,
        name: 'Part 2: Am-F 아르페지오',
        startStep: 32,
        endStep: 63,
        instruments: ['🎹 피아노 아르페지오'],
        description: '감성적인 Am-F 아르페지오',
      },
      {
        partNum: 3,
        name: 'Part 3: 킥 & 신스베이스',
        startStep: 64,
        endStep: 95,
        instruments: ['🎹 피아노', '🥁 4박 킥', '⚡ 신스베이스', '🧗‍♀️ 쏘우 리드'],
        description: '비트와 쏘우투스 리드 선율 추가',
      },
      {
        partNum: 4,
        name: 'Part 4: 등반 리드 피날레',
        startStep: 96,
        endStep: 127,
        instruments: ['🎹 피아노', '🥁 킥', '⚡ 신스베이스', '🧗‍♀️ 풀 리드'],
        description: '128스텝 완성형 등반 루프',
      },
    ],
  },
  climb: {
    totalSteps: 64,
    bpm: 112,
    stepDuration: 0.1339,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 112BPM 킥 & 펄스',
        startStep: 0,
        endStep: 15,
        instruments: ['⚡ 트라이앵글 베이스', '🥁 킥 드럼'],
        description: '112BPM 기본 펄스',
      },
      {
        partNum: 2,
        name: 'Part 2: 16분음표 아르페지오',
        startStep: 16,
        endStep: 31,
        instruments: ['⚡ 베이스', '🥁 킥', '✨ 아르페지오'],
        description: '16분음표 아르페지오 러닝',
      },
      {
        partNum: 3,
        name: 'Part 3: 코드 스탭',
        startStep: 32,
        endStep: 47,
        instruments: ['⚡ 베이스', '✨ 아르페지오', '🔥 스탭 코드'],
        description: '에너지 넘치는 코드 스탭',
      },
      {
        partNum: 4,
        name: 'Part 4: 풀 펄스 순환',
        startStep: 48,
        endStep: 63,
        instruments: ['⚡ 베이스', '🥁 킥', '✨ 아르페지오', '🔥 풀 스탭'],
        description: '64스텝 순환 루프',
      },
    ],
  },
  shop: {
    totalSteps: 64,
    bpm: 100,
    stepDuration: 0.15,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 보사노바 베이스',
        startStep: 0,
        endStep: 15,
        instruments: ['🎸 어쿠스틱 베이스', '🪕 우쿨렐레 스트럼'],
        description: '보사노바 리듬 베이스와 기타',
      },
      {
        partNum: 2,
        name: 'Part 2: 실로폰 멜로디',
        startStep: 16,
        endStep: 31,
        instruments: ['🎸 베이스', '🪕 스트럼', '🔔 실로폰 멜로디'],
        description: '통통 튀는 실로폰 선율',
      },
      {
        partNum: 3,
        name: 'Part 3: 우드블록 퍼커션',
        startStep: 32,
        endStep: 47,
        instruments: ['🎸 베이스', '🪕 스트럼', '🔔 실로폰', '🪵 우드블록'],
        description: '우드블록 탭 리듬 추가',
      },
      {
        partNum: 4,
        name: 'Part 4: 아늑한 휴식처',
        startStep: 48,
        endStep: 63,
        instruments: ['🎸 풀 베이스', '🪕 풀 스트럼', '🔔 실로폰'],
        description: '따뜻한 만물상 루프',
      },
    ],
  },
  victory: {
    totalSteps: 64,
    bpm: 100,
    stepDuration: 0.15,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 승리의 브라스',
        startStep: 0,
        endStep: 15,
        instruments: ['🎺 브라스 화음'],
        description: '100BPM 브라스 팡파르',
      },
      {
        partNum: 2,
        name: 'Part 2: 하프 아르페지오',
        startStep: 16,
        endStep: 31,
        instruments: ['🎺 브라스', '✨ 하프 아르페지오'],
        description: '상승 하프 아르페지오',
      },
      {
        partNum: 3,
        name: 'Part 3: 팡파르 화음 전개',
        startStep: 32,
        endStep: 47,
        instruments: ['🎺 풀 브라스', '✨ 하프'],
        description: '화려한 승리 화음',
      },
      {
        partNum: 4,
        name: 'Part 4: 완등 피날레',
        startStep: 48,
        endStep: 63,
        instruments: ['🎺 풀 브라스', '✨ 풀 하프'],
        description: '정상 완등 승리 루프',
      },
    ],
  },
  crisis: {
    totalSteps: 32,
    bpm: 126,
    stepDuration: 0.119,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 더블 심장박동',
        startStep: 0,
        endStep: 7,
        instruments: ['💓 심장박동 (쿵-쾅)'],
        description: '160Hz->55Hz 심장박동',
      },
      {
        partNum: 2,
        name: 'Part 2: 째깍 초침',
        startStep: 8,
        endStep: 15,
        instruments: ['💓 심장박동', '⏱️ 째깍 하이햇'],
        description: '시계 초침 소리 추가',
      },
      {
        partNum: 3,
        name: 'Part 3: 텐션 패드',
        startStep: 16,
        endStep: 23,
        instruments: ['💓 심장박동', '🌫️ 텐션 코드'],
        description: '디미니쉬 텐션 화음',
      },
      {
        partNum: 4,
        name: 'Part 4: 긴급 위기 서스펜스',
        startStep: 24,
        endStep: 31,
        instruments: ['💓 심장박동', '⏱️ 초침', '🌫️ 텐션'],
        description: '스태미나 위기 루프',
      },
    ],
  },
  puzzle: {
    totalSteps: 32,
    bpm: 92,
    stepDuration: 0.163,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 재즈 코드 인트로',
        startStep: 0,
        endStep: 7,
        instruments: ['🎹 재즈 코드'],
        description: '부드러운 재즈 코드',
      },
      {
        partNum: 2,
        name: 'Part 2: 마림바 패턴 A',
        startStep: 8,
        endStep: 15,
        instruments: ['🎹 코드', '🔔 마림바 멜로디'],
        description: '통통 튀는 마림바 선율',
      },
      {
        partNum: 3,
        name: 'Part 3: 마림바 패턴 B',
        startStep: 16,
        endStep: 23,
        instruments: ['🎹 코드', '🔔 마림바 변주'],
        description: '마림바 변주 프레이즈',
      },
      {
        partNum: 4,
        name: 'Part 4: 포커스 순환',
        startStep: 24,
        endStep: 31,
        instruments: ['🎹 풀 코드', '🔔 마림바'],
        description: '집중 퀴즈 루프',
      },
    ],
  },
  chill: {
    totalSteps: 8,
    bpm: 27,
    stepDuration: 2.2,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 4화음 앰비언트 패드',
        startStep: 0,
        endStep: 1,
        instruments: ['🏔️ 4화음 웜 패드'],
        description: '포근한 앰비언트 코드',
      },
      {
        partNum: 2,
        name: 'Part 2: 힐링 화음 전개',
        startStep: 2,
        endStep: 3,
        instruments: ['🏔️ 앰비언트 패드'],
        description: '서정적 화음 전개',
      },
      {
        partNum: 3,
        name: 'Part 3: 듀엣 멜로디 & 스파클',
        startStep: 4,
        endStep: 5,
        instruments: ['🏔️ 패드', '✨ 멜로디', '🔔 스파클'],
        description: '반짝이는 스파클과 선율',
      },
      {
        partNum: 4,
        name: 'Part 4: 젠 하모닉스',
        startStep: 6,
        endStep: 7,
        instruments: ['🏔️ 풀 패드', '✨ 풀 멜로디'],
        description: '깊은 힐링 루프',
      },
    ],
  },
  arcade: {
    totalSteps: 32,
    bpm: 110,
    stepDuration: 0.136,
    parts: [
      {
        partNum: 1,
        name: 'Part 1: 트라이앵글 칩 베이스',
        startStep: 0,
        endStep: 7,
        instruments: ['📐 트라이앵글 베이스'],
        description: '8비트 칩튠 베이스라인',
      },
      {
        partNum: 2,
        name: 'Part 2: 8비트 사인 리드',
        startStep: 8,
        endStep: 15,
        instruments: ['📐 베이스', '👾 사인파 리드'],
        description: '레트로 게임 선율',
      },
      {
        partNum: 3,
        name: 'Part 3: 리드 변주',
        startStep: 16,
        endStep: 23,
        instruments: ['📐 베이스', '👾 리드 선율'],
        description: '아케이드 멜로디 전개',
      },
      {
        partNum: 4,
        name: 'Part 4: 레트로 순환',
        startStep: 24,
        endStep: 31,
        instruments: ['📐 풀 베이스', '👾 풀 리드'],
        description: '클래식 아케이드 루프',
      },
    ],
  },
};
