-- 20260329000004_fix_security_infrastructure.sql

-- [1] Security Audit Log Table (계조/존재 여부 확인 후 생성)
CREATE TABLE IF NOT EXISTS public.security_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    event_data JSONB DEFAULT '{}'::jsonb,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 로그 테이블 RLS 활성화
ALTER TABLE public.security_audit_log ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 로그만 볼 수 있거나, 혹은 쓰기만 가능하도록 설정 (보통 쓰기 전용)
CREATE POLICY "Users can insert own audit logs" ON public.security_audit_log
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own audit logs" ON public.security_audit_log
    FOR SELECT USING (auth.uid() = user_id);

-- [2] user_level_records RLS 강화
-- 직접적인 INSERT/UPDATE/DELETE를 차단하고 전용 RPC(submit_game_result)를 통해서만 변경되도록 합니다.
-- (기존 정책이 있다면 제거 후 신규 적용)
DROP POLICY IF EXISTS "Users can insert own level records" ON public.user_level_records;
DROP POLICY IF EXISTS "Users can update own level records" ON public.user_level_records;
DROP POLICY IF EXISTS "Users can delete own level records" ON public.user_level_records;

-- 조회는 허용하되, 변경은 app.bypass_profile_security와 유사한 메커니즘 혹은 RPC 권한으로 제어
-- 여기서는 profiles와 동일하게 헬퍼 설정을 감시합니다.
CREATE POLICY "Level records are only updatable via secure RPC" ON public.user_level_records
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (
        current_setting('app.bypass_profile_security', true) = '1'
    );

-- [3] inventory RLS 강화
-- 수동 아이템 수량 조작 방지
DROP POLICY IF EXISTS "Users can update own inventory" ON public.inventory;

CREATE POLICY "Inventory is only updatable via secure RPC" ON public.inventory
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (
        current_setting('app.bypass_profile_security', true) = '1'
    );

-- [4] Helper function update
-- log_security_event가 이제 확실히 존재하는 테이블을 참조하도록 보장됨
